[model]
custom = false
name = "resnet50"
pretrained = true

[data]
processed_dir = "data/processed/llb11"
annotation_file = "data/raw/llb11/llb11_annot.csv"
batch_size = 16

[training]
epochs = 40
learning_rate = 5e-5
weight_decay = 1e-5
patience = 8
use_saved_model = false
use_sampler = true

[logging]
model_dir = "models_checkpoints"
log_dir = "logs"
