[model]
name = "convnext_tiny"
pretrained = true

[data]
processed_dir = "data/processed/llb11"
annotation_file = "data/raw/llb11/llb11_annot.csv"
batch_size = 4

[training]
epochs = 50
learning_rate = 3e-5
weight_decay = 1e-6
patience = 10
use_saved_model = false
use_sampler = true

[logging]
model_dir = "models_checkpoints"
log_dir = "logs"
